In [1]:
import numpy as np

In [26]:
x = np.array([1, 2, 3])

In [30]:
x.shape

(3,)

In [18]:
y = np.array([[1, 2, 3], 
             [4, 5, 6],
             [7, 8, 9]])

In [23]:
y.shape[1]

3

In [4]:
x

array([1, 2, 3])

# --- RNN parameters ---


In [5]:
input_dim = 1
hidden_dim = 2
output_dim = 1

In [ ]:
np.random.seed(42)

# random seed used when generating random numbers, so that the same random numbers are generated every time the code is run

In [33]:
w_x = np.random.rand(input_dim, hidden_dim)
# weights for the input to hidden layer connections

In [ ]:
w_h = np.random.rand(hidden_dim, hidden_dim)
# hiden to hidden layer connections beccause we will be using the hidden state from the previous time step as input to the current time step

In [8]:
w_y = np.random.rand( output_dim, hidden_dim)

In [38]:
b_h = np.random.rand(hidden_dim)
# bias for the hidden layer 
b_y = np.random.rand(output_dim)
# bias for the output layer

In [10]:
h_prev = np.zeros(hidden_dim)
# initial hidden state, initialized to zeros

In [31]:
x.shape[0]
# we used shape[0] because we want the number of rows in the input, which corresponds to the number of time steps in the sequence.

3

In [51]:
for t in range(x.shape[0]):
    x_t = x[t]
# in each time step, we take the corresponding input from the sequence x, which is x[t], and store it in x_t. 
#  allows us to process each time step of the input sequence sequentially in the loop.
    x_t = x[t].reshape(1, -1)
# reshape x_t to have a shape of (1, input_dim) so that it can be multiplied with the weight matrices w_x and w_h.
    h_t = np.tanh(np.dot(x_t, w_x) + np.dot(h_prev, w_h) + b_h)
    # compute the hidden state at time step t using the input x_t, the previous hidden state h_prev, and the weights and biases.
    y_t = np.dot(h_t, w_y.T) + b_y
    # compute the output at time step t using the hidden state h_t and the weights and biases for the output layer. 
    # T is used to transpose w_y so that the dimensions match for the matrix multiplication.
    h_prev = h_t
    print(f"Time step {t}:")
    print(f"Input x_t: {x_t}")
    print(f"Hidden state h_t: {h_t}")
    print(f"Output y_t: {y_t}")

Time step 0:
Input x_t: [[1]]
Hidden state h_t: [[0.96999556 0.99593729]]
Output y_t: [[1.1150955]]
Time step 1:
Input x_t: [[2]]
Hidden state h_t: [[0.9723735  0.99877613]]
Output y_t: [[1.11590934]]
Time step 2:
Input x_t: [[3]]
Hidden state h_t: [[0.97494087 0.99963961]]
Output y_t: [[1.1164446]]


In [52]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'inquilab zindabad']
# Yeh ek list hai sentences ki (text data)
# Ab humein in sentences ko numbers mein convert karna hai taaki machine samajh sake

In [53]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokens = Tokenizer()

In [54]:
tokens.fit_on_texts(docs)
# fit_on_texts method se hum apne text data ko analyze karte hain aur ek word index banate hain, jismein har unique word ko ek unique integer assign kiya jata hai.
# Isse humare paas ek mapping ban jata hai words aur integers ke beech,

In [55]:
tokens.word_index

{'india': 1,
 'jeetega': 2,
 'hip': 3,
 'kohli': 4,
 'sachin': 5,
 'dhoni': 6,
 'go': 7,
 'hurray': 8,
 'bhai': 9,
 'bharat': 10,
 'mata': 11,
 'ki': 12,
 'jai': 13,
 'inquilab': 14,
 'zindabad': 15}

In [56]:
tokens.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jai', 1),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('inquilab', 1),
             ('zindabad', 1)])

In [ ]:
tokens.document_count
# document_count attribute se hum apne text data mein total number of documents (sentences) ko count karte hain.

9

In [59]:
sequence = tokens.texts_to_sequences(docs)
sequence

[[7, 1],
 [1, 1],
 [3, 3, 8],
 [2, 9, 2, 1, 2],
 [10, 11, 12, 13],
 [4, 4],
 [5, 5],
 [6, 6],
 [14, 15]]

In [60]:
from tensorflow.keras.utils import pad_sequences
padded_sequence = pad_sequences(sequence, padding='post')

In [61]:
padded_sequence

array([[ 7,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3,  8,  0,  0],
       [ 2,  9,  2,  1,  2],
       [10, 11, 12, 13,  0],
       [ 4,  4,  0,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [14, 15,  0,  0,  0]], dtype=int32)

In [62]:
from tensorflow.keras.datasets import imdb
from keras import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [63]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

C:\Users\Edunet Foundation\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_format_impl.py:838: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  array = pickle.load(fp, **pickle_kwargs)


In [77]:
len(x_train[5])

50

In [64]:
X_train.shape

(25000,)

In [65]:
X_test.shape

(25000,)

In [81]:
x_train[3].shape

(50,)

In [85]:
x_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [ ]:
x_train = pad_sequences(X_train, padding='post', maxlen=50)
x_test = pad_sequences(X_test, padding='post', maxlen=50)


In [ ]:
model = Sequential()
model.add(SimpleRNN(32, input_shape=(50,1)))
model.add(Dense(1, activation='sigmoid'))
model.summary()

C:\Users\Edunet Foundation\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [87]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)